### ISSUE TITLE
Use the manylinux Docker image

### ISSUE THREAD

**Issue by probonopd** [niess/linuxdeploy-plugin-python#12]
Could we use the manylinux2010 Docker image (PEP 571) as the Docker image used for building Python AppImages?

References:
* https://www.python.org/dev/peps/pep-0571/
* https://quay.io/repository/pypa/manylinux2010_x86_64?tag=latest&tab=tags

**Comment by anki-code** [comment]
@probonopd just interesting what profit for appimages?

**Comment by probonopd** [comment]
AppImages made using that Python would be compliant to PEP 571.

**Comment by niess** [comment]
Hello @probonopd . I started working on this. My main problem for now is that I need to migrate from `apt` to `yum` since the manylinux image seems to be CentOS based. So I have to find the equivalent packages for the Python install ([L9-14](https://github.com/niess/linuxdeploy-plugin-python/blob/master/.travis/Dockerfile#L9) of the Dockerfile). Do you know if there is a conversion utility that exists? For now its a game of trial and guesses but with ~15 min waiting between 2 trials :(

Actually I am surprised that the manylinux image doesn't have all the dependencies needed for installing Python?

**Comment by probonopd** [comment]
According to https://linuxconfig.org/compile-and-install-python-3-on-centos-7-linux-from-source

    yum-builddep python

will install all Python build prerequisites to meet all compilation requirements.

**Comment by niess** [comment]
@probonopd I finally managed to build the images for manylinux (CentOs6). Unfortunately the `yum-builddep python` command didn't work with the manylinux container. Also I had to tweak a bit the `linuxdeploy-plugin-python.sh` script for being able to run on CentOS6 (e.g. `ln -r` is not supported, the data of dependencies are located in different paths than for Debian/Ubuntu, etc.). But by trials and errors it finally worked out after 8 hours of struggle.

@anki-code I also updated the RPATH of the python executables. Now they properly point to `$APPDIR/usr/lib` using a relative path inside the image. For example you can check this by extracting the image and running `objdump -p squashfs-root/usr/python/bin/pythonX.Y`. Hopefully I didn't introduce extra bugs :P

**Comment by probonopd** [comment]
Great progress @niess. Very, very useful. Could you make the filenames more standard please, e.g., `python- 3.7.3-x86_64.AppImage` instead of `python3-x86_64.AppImage'`?

**Comment by niess** [comment]
Hello @probonopd. I could yes, but as so it would imply more maintenance (e.g. update the README at each version change). Also then one could consider generating several images for a given major version, e.g. 3.7, 3.8, etc. That's why I initially decided to stick to two images only: one for Python2 and one for Python3 containing the stable HEAD of each, in principle and labelled `2` and `3`. I'm probably outdated already. To get the full version one could do: `python3-x86_64.AppImage --version`.

Yet, I could try to automate this. But I find GitHub/Travis CI not so convenient for that with 2 simultaneous jobs for all my projects and build times of ~15-20 min. I would rather use a private server with Docker (or equivalent) that could generate a bunch of images from a list of full versions/recipes, update the git/README and upload the images (to GitHub?)

Another idea that I had, is that one could generate a Python image from another one. Right now I'm recompiling the whole Python source at each image, even though they use the same source. Eg. for the `scipy` image I build Python3 two times. It would be more efficient if one could provide a base AppImage instead. Then the build script would just `appimage-extract` the image, pip install what's missing -prune/rebase- and repackage the result. Being able to do so would speed up and ease the creation of new Python based images.

**Comment by probonopd** [comment]
> Yet, I could try to automate this. But I find GitHub/Travis CI not so convenient for that with 2 simultaneous jobs for all my projects and build times of ~15-20 min.

You know that you can have a build matrix with many more than 2?
https://docs.travis-ci.com/user/build-matrix/

Also, I think it's fine to have just the latest Python versions, if they would be named fully.

**Comment by niess** [comment]
indeed for the build matrix. Yet physically I still only have 2 simultaneous workers on Travis for all my projects :(

Anyway, I updated the Python versions and added a 3.8 Python AppImage. The names of the bare Python images also include the full version tag now.

@anki-code Take care that as it is for now updating the version of the bare Python images requires to modify many files: the [recipe](appimage/recipes) filename and its content, the [.travis/script.sh](.travis/script.sh) file, the [tests/test-plugin.py](tests/test-plugin.py) script and the [README.md](README.md). This could probably be improved with extra developments, i.e. time. But for now it's more efficient for me to just `grep -r` & manually change all the occurrences of the version tag.
