### ISSUE TITLE
Python 3.8 support

### ISSUE THREAD

**Issue by anki-code** [niess/linuxdeploy-plugin-python#14]
Since [3.8 was released](https://docs.python.org/3.8/whatsnew/3.8.html) I've tried to build xonsh and it looks like work as expected. But I see that internal python structure was changed in 3.8 and I think this will require some changes in the plugin. For example there are no `.libs` directories in `site-packages` as `scipy` recipe described. Probably something more require changes.

**Comment by niess** [comment]
@anki-code Thanks for the feedback concerning scipy & Python 3.8. For now I decided to stick to 3.7 for the scipy image because `3.8.0` seems a bit too fresh and there will probably be issues with some packages not being compatible for now. So I'd rather wait for a more mature release of 3.8  (i.e. other people debugging this :P) before migrating the scipy image to 3.8. I updated it to Python 3.7.5 however.

Please, feel free to update/PR the xonsh image to 3.8 if you like? Or I can do it if you want?

**Comment by anki-code** [comment]
@niess thanks for update!
I've built and test the xonsh on 3.8 with recipe:
```
export PYTHON_VERSION="3.8.0"
export PIP_REQUIREMENTS="xonsh prompt_toolkit gnureadline Pygments"
export PYTHON_ENTRYPOINT='"-u" "-c" "from xonsh.main import main; main()"'
```
Feel free to add it or just replace old recipe. Thanks!

**Comment by niess** [comment]
@anki-code I've updated the xonsh recipe. I'll keep this issue open for now as a remainder for the scipy image.

**Comment by anki-code** [comment]
Thanks! I use it in [xonssh/xxh](https://github.com/xonssh/xxh) now!
