### ISSUE TITLE
Why does hashlib not exist?

### ISSUE THREAD

**Issue by zhoujin7** [niess/linuxdeploy-plugin-python#16]
![image](https://user-images.githubusercontent.com/8288988/69778002-aad8c900-11dd-11ea-9692-19964927cfda.png)
I use Pycharm create a virtual env, use python3.7.5-x86_64.AppImage as base Interpreter.

**Comment by niess** [comment]
Hello @zhoujin7 . For me the following works:
```
./python3.7.5-x86_64.AppImage app.py
```
with `app.py` as above. I also checked that `hashlib` is inside the image, located at `${APPDIR}/usr/python/lib/python3.7/hashlib.py`.

What error message do you get?

**Comment by zhoujin7** [comment]
The hashlib is inside the image,  but Pycharm seems can't realize it.
No meaningful error reported.  Pycharm tips "No module names hashlib".
I have to install Pythian3.7 by apt.

**Comment by niess** [comment]
That's strange. Sorry I don't use PyCharm and never noticed this issue. Yet I wonder why PyCharm doesn't see the image native modules?

**Comment by niess** [comment]
@zhoujin7 I just tried it with PyCharm. On my side it does run setting python to the python appimage executable BUT the Linter reports an error probably because it doesn't see the modules inside the AppImage. So the editor reports an error while it actually works if you run it.

If it is possible to configure the Linter search path you could:
1. extract the AppImage:  `python3.7.5-x86_64.AppImage --appimage-extract`
2. configure the Linter search path to point to the extracted path: `squashfs-root`

**Comment by zhoujin7** [comment]
@niess Thanks for your help. I'll try it. ㋛㋛㋛
