### ISSUE TITLE
Use separate prefix inside AppDir/usr

### ISSUE THREAD

**Issue by TheAssassin** [niess/linuxdeploy-plugin-python#7]
You might have noticed that in the conda plugin, we use `usr/conda/` as installation prefix. The reason is, conda ships libraries that might break other applications in the AppDir by e.g., clashing with libraries deployed by linuxdeploy normally.

I presume this plugin might be affected by that, too, since libraries are downloaded from the Internet and just put into the AppDir.

There's the unwritten rule that plugins shall not break each other and that different application types should be able to coexist in the AppDir. Therefore, I suggest you to use e.g., `usr/python` or `usr/python<version>/` and put `lib`, `share` etc. into that instead of using `usr/` directly.

**Comment by niess** [comment]
Indeed :) Right now I'm spamming the usr/bin and /usr/lib spaces which was very convenient so far :P Doing as you say would allow several Python version to coexists as well, if needed. Yet, I first have to solve some issues that for, related to interporating with linuxdeploy. I'll submit them as questions on the linuxdeploy page.

**Comment by niess** [comment]
Done with 6ec41569cda3e65640cb72cab566376e065d42a4. The python install has been rebased to `AppDir/usr/python`. A priori it should be possible to install multiple Python versions as well, since Python support this natively. Yet this was not tested.

In addition C-extension modules and packaged libraries (e.g. by Numpy) are patched as well. Libraries are symlinked to `AppDir/usr/bin` and the RPATH of C-extension modules points to `AppDir/usr/bin` (using a relative path). In both cases externals dependencies are packaged as well, except if in the AppImage [exclusion list](https://raw.githubusercontent.com/probonopd/AppImages/master/excludelist).
